name: ğŸ“š Generate Changelog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:     # PossibilitÃ  di lanciarlo manualmente

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: ğŸ“¦ Install dependencies
        run: |
          gem install github_changelog_generator

      - name: ğŸ“š Generate CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          github_changelog_generator \
            --user francesco-loreti \
            --project pdnd-ruby-client \
            --token $GITHUB_TOKEN

      - name: ğŸ” Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "ğŸ“š Update CHANGELOG.md"
          git push